export type FeedbackSource = "12365auto" | "dongchedi" | "xiaohongshu" | "media" | "official";
export type MarketSignal = "insufficient-evidence" | "watch" | "verify-before-buy" | "pause" | "resolved";
export interface FeedbackRecord { id: string; source: FeedbackSource; sourceUrl?: string; brand: string; series: string; modelYear?: string; trimId?: string; submittedAt?: string; summary: string; categories: string[]; manufacturerResponse?: string; status?: string; evidenceIds: string[]; }
export interface FeedbackCluster { id: string; brand: string; series: string; modelYears: string[]; trimIds: string[]; topic: string; records: FeedbackRecord[]; firstSeenAt?: string; lastSeenAt?: string; sourceCount: number; signal: MarketSignal; rationale: string; evidenceIds: string[]; }
const normalize = (value: string) => value.normalize("NFKC").toLowerCase().replace(/[，。！？、,:：;；\s]+/g, "");
export function clusterFeedback(records: readonly FeedbackRecord[]): FeedbackCluster[] {
  const groups = new Map<string, FeedbackRecord[]>();
  for (const record of records) { const topic = record.categories[0] ?? record.summary.slice(0, 18); const key = `${normalize(record.brand)}:${normalize(record.series)}:${normalize(topic)}`; groups.set(key,[...(groups.get(key) ?? []),record]); }
  return [...groups].map(([key, items]) => { const first=items.map(x=>x.submittedAt).filter(Boolean).sort()[0]; const last=items.map(x=>x.submittedAt).filter(Boolean).sort().at(-1); const sources=new Set(items.map(x=>x.source)); const resolved=items.some(x=>/解决|修复|完成整改|召回/.test(x.manufacturerResponse ?? "")); const signal: MarketSignal = resolved ? "resolved" : items.length >= 3 && sources.size >= 2 ? "verify-before-buy" : items.length >= 3 ? "watch" : "insufficient-evidence"; return { id:`feedback:${key}`,brand:items[0]!.brand,series:items[0]!.series,modelYears:[...new Set(items.map(x=>x.modelYear).filter((x):x is string=>Boolean(x)))],trimIds:[...new Set(items.map(x=>x.trimId).filter((x):x is string=>Boolean(x)))],topic:items[0]!.categories[0] ?? items[0]!.summary.slice(0,18),records:items,...(first ? {firstSeenAt:first} : {}),...(last ? {lastSeenAt:last} : {}),sourceCount:sources.size,signal,rationale:`${items.length} records from ${sources.size} source(s); manufacturer resolution=${resolved}`,evidenceIds:[...new Set(items.flatMap(x=>x.evidenceIds))]}; });
}
