import { randomUUID } from "node:crypto";
import { aggregateSourceHealth, BackendRouter, createFailure, ManualStepBackend, OpenCliBackend, probeOperationHealth, type OperationDescriptor, type SourceAdapter, type SourceHealthRuntime, type SourceRequest, type SourceResult, type SourceRuntime, validateSourceRequest } from "@sourceport/core";
const manifest={source:"12365auto",displayName:"车质网",version:"1.0.0",description:"Read-only vehicle complaint and complaint ranking acquisition"} as const;
const complaintShape={type:"object",additionalProperties:false,required:["complaintId","brand","series","model","summary","submittedAt","status","url"],properties:{complaintId:{type:"string"},brand:{type:"string"},series:{type:"string"},model:{type:"string"},modelYear:{type:"string"},summary:{type:"string"},categories:{type:"array",items:{type:"string"}},submittedAt:{type:"string"},status:{type:"string"},manufacturerResponse:{type:"string"},url:{type:"string"}}};
const search:OperationDescriptor={source:manifest.source,operation:"search-complaints",description:"Search 12365auto complaints",access:"read",schemaVersion:"1.0.0",parametersSchema:{type:"object",additionalProperties:false,required:["query"],properties:{query:{type:"string",minLength:1},limit:{type:"integer",minimum:1,maximum:50},startDate:{type:"string"},endDate:{type:"string"}}},outputSchema:{type:"object",required:["query","items"],properties:{query:{type:"string"},items:{type:"array",items:complaintShape}}},backends:[{name:"12365auto-browser",kind:"opencli",priority:0},{name:"12365auto-manual",kind:"manual-step",priority:99}],auth:"optional",freshnessClass:"volatile"};
const detail:OperationDescriptor={source:manifest.source,operation:"get-complaint",description:"Retrieve one 12365auto complaint",access:"read",schemaVersion:"1.0.0",parametersSchema:{type:"object",additionalProperties:false,required:["complaint"],properties:{complaint:{type:"string",minLength:1}}},outputSchema:{type:"object",required:["item"],properties:{item:complaintShape}},backends:search.backends,auth:"optional",freshnessClass:"periodic"};
const ratio:OperationDescriptor={source:manifest.source,operation:"get-complaint-sales-ratio",description:"Retrieve complaint-to-sales ranking",access:"read",schemaVersion:"1.0.0",parametersSchema:{type:"object",additionalProperties:false,properties:{query:{type:"string"},limit:{type:"integer",minimum:1,maximum:50}}},outputSchema:{type:"object",required:["items"],properties:{items:{type:"array"}}},backends:search.backends,auth:"optional",freshnessClass:"volatile"};
const ranking:OperationDescriptor={source:manifest.source,operation:"get-ranking",description:"Retrieve 12365auto complaint ranking",access:"read",schemaVersion:"1.0.0",parametersSchema:{type:"object",additionalProperties:false,properties:{query:{type:"string"},limit:{type:"integer",minimum:1,maximum:50}}},outputSchema:{type:"object",required:["items"],properties:{items:{type:"array",items:{type:"object",required:["brand","series","count"],properties:{brand:{type:"string"},series:{type:"string"},count:{type:"integer"},replyRate:{type:"number"}}}}}},backends:search.backends,auth:"optional",freshnessClass:"volatile"};
function clean(v:unknown){return String(v??"").replace(/\s+/g," ").trim();}
function rows(data:unknown){return Array.isArray(data)?data.filter(x=>x&&typeof x==="object"):[];}
function complaintData(data:unknown, query:string){const items=rows(data).flatMap((x:any)=>{const url=clean(x.url); const id=clean(x.complaintId??x.id); if(!id||!url)return []; return [{complaintId:id,brand:clean(x.brand),series:clean(x.series),model:clean(x.model),...(x.modelYear?{modelYear:clean(x.modelYear)}:{}),summary:clean(x.summary??x.problem),categories:Array.isArray(x.categories)?x.categories.map(clean):[],submittedAt:clean(x.submittedAt??x.date),status:clean(x.status),...(x.manufacturerResponse?{manufacturerResponse:clean(x.manufacturerResponse)}:{}),url}];}); if(!items.length)throw new Error("12365auto returned no usable complaints"); return {query,items};}
function ratioData(data:unknown){const items=rows(data).map((x:any)=>({brand:clean(x.brand),series:clean(x.series),complaintCount:Number(x.complaintCount??x.count)||0,salesCount:Number(x.salesCount??x.sales)||0,ratio:Number(x.ratio??x.complaintSalesRatio)||0})); if(!items.length) throw new Error("12365auto returned no usable complaint sales ratios"); return {items};}
function invalid(req:SourceRequest,d:OperationDescriptor,msg:string):SourceResult{return {requestId:req.requestId??randomUUID(),source:manifest.source,operation:req.operation,operationSchemaVersion:d.schemaVersion,status:"failed",evidence:[],warnings:[],failure:createFailure("invalid_request",msg,"validation"),recoveryActions:[]};}
export class Auto12365Adapter implements SourceAdapter { readonly #router:BackendRouter; constructor(openCliCommand?:string){const command=openCliCommand?{command:openCliCommand}:{}; const backend=(op:string)=>new OpenCliBackend({name:`12365auto-browser-${op}`,...command,jsonOutput:true,args:({request})=>{const p=request.parameters as Record<string,unknown>; return op==="search"?["12365auto","complaints",String(p.query),"--limit",String(p.limit??20)]:op==="detail"?["12365auto","complaint",String(p.complaint)]:op==="ratio"?["12365auto","complaint-sales-ratio",...(p.query?[String(p.query)]:[]),"--limit",String(p.limit??20)]:["12365auto","ranking","--limit",String(p.limit??20)];},parse:(data,ctx)=>op==="search"?complaintData(data,String((ctx.request.parameters as any).query)):op==="detail"?{item:complaintData([data],String((ctx.request.parameters as any).complaint)).items[0]}:op==="ratio"?ratioData(data):({items:rows(data).map((x:any)=>({brand:clean(x.brand),series:clean(x.series),count:Number(x.count)||0,...(x.replyRate!==undefined?{replyRate:Number(x.replyRate)}:{})}))})}); this.#router=new BackendRouter([backend("search"),backend("ratio"),new ManualStepBackend({name:"12365auto-manual",description:"Restore 12365auto browser access or complete verification, then retry"})]);}
manifest(){return manifest;} operations(){return [search,detail,ranking,ratio];} async execute(req:SourceRequest,_runtime:SourceRuntime){const d=this.operations().find(x=>x.operation===req.operation);if(!d)return invalid(req,search,`Unsupported operation '${req.operation}'`);const v=validateSourceRequest(req,d.parametersSchema);if(!v.ok)return {...invalid(req,d,v.failure.message),failure:v.failure};return this.#router.execute(v.value,d);} async health(runtime:SourceHealthRuntime){const started=runtime.now();const probes = await Promise.all(this.operations().map((operation) => probeOperationHealth({ operation, router: this.#router, parameters: operation.operation === "search-complaints" ? { query: "汽车投诉", limit: 1 } : operation.operation === "get-complaint" ? { complaint: "probe" } : { query: "汽车", limit: 1 }, runtime }))); return aggregateSourceHealth({source:manifest.source,displayName:manifest.displayName,checkedAt:started.toISOString(),durationMs:runtime.now().getTime()-started.getTime(),operations:probes});}}
export const __test__={complaintData};
